version: '3'

services:
  bouncer-mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bouncer
      - MYSQL_USER=bouncer
      - MYSQL_PASSWORD=admin
    volumes:
      - bouncer-mysql-volume:/var/lib/mysql
    ports:
      - "3306:3306"

  user-service:
    build: user-service
    restart: on-failure
    env_file: .env
    ports:
      - "8082:8082"

  gateway-service:
    build: gateway
    restart: on-failure
    env_file: .env
    ports:
      - "8080:8080"

  bouncer-service:
    build: bouncer
    restart: on-failure
    env_file: .env
    depends_on:
      - bouncer-mysql
    volumes:
      - ./data:/data
    ports:
      - "8081:8081"

volumes:
  bouncer-mysql-volume:
    