version: '3'

services:
  bouncer-mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bouncer
      - MYSQL_USER=bouncer
      - MYSQL_PASSWORD=admin
    volumes:
      - bouncer-mysql-volume:/var/lib/mysql
    ports:
      - "3306:3306"

  webhook-mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=webhook
      - MYSQL_USER=bouncer
      - MYSQL_PASSWORD=admin
      - MYSQL_TCP_PORT=3308
    volumes:
      - webhook-mysql-volume:/var/lib/mysql
    ports:
      - "3308:3308"

  webhook-service:
    build: webhook-service
    restart: on-failure
    env_file: .env
    ports:
      - "8084:8084"
    depends_on:
      - webhook-mysql

  gateway-service:
    build: gateway
    restart: on-failure
    env_file: .env
    ports:
      - "8080:8080"

  bouncer-service:
    build: bouncer
    restart: on-failure
    env_file: .env
    depends_on:
      - bouncer-mysql
    volumes:
      - ./data:/data
    ports:
      - "8081:8081"

  preset-mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=preset
      - MYSQL_USER=bouncer
      - MYSQL_PASSWORD=admin
      - MYSQL_TCP_PORT=3307
    volumes:
      - preset-mysql-volume:/var/lib/mysql
    ports:
      - "3307:3307"

  preset-service:
    build: preset-service
    restart: on-failure
    env_file: .env
    depends_on:
      - preset-mysql
    ports:
      - "8083:8083"

volumes:
  bouncer-mysql-volume:
  preset-mysql-volume:
  webhook-mysql-volume:
